### ISSUE TITLE
does not find the function

### ISSUE THREAD

**Issue by Eztero** [Emurgo/react-native-haskell-shelley#13]
hi, I was trying to test the libraries by calling them from c ++ using the dynamic .so library that was compiled in the rust folder. but apparently it does not recognize the function when compiling.

I want to compile this test code:
```
#include "react_native_haskell_shelley.h" 
...........
int main(){
std::string b32="addr1qxxxxxxxxxxxxxxxxxxxx";
bool estado;
const char **error=nullptr;
RPtr q;
estado=address_from_bech32(b32.c_str(), &q, error);
std::cout<<error<<std::endl;
std::cout<<estado<<std::endl; 
return 0;
}
```
I compile with this command (the library is in the same folder)

`g++ -Wall -o test main.cpp -L. -lreact_native_haskell_shelley`

I get this error
```
/tmp/cceT6kUo.o: En la función `main':
main.cpp:(.text+0xa1): referencia a `address_from_bech32' sin definir
collect2: error: ld returned 1 exit status
```

**Comment by v-almonacid** [comment]
We don't use this lib directly from C/C++ so I can't provide much feedback. However, I think it's failing because you might not be respecting the function signature. Also, be aware that compiling the library using the default configuration creates C headers, not C++ (but I guess they should be compatible in C++ (?)).  You can change this in `cbindgen.toml` to make sure you are generating C++ headers.

**Comment by Eztero** [comment]
try both settings (c and c ++) in `cbindgen.tom` file but i get same error.
How do you make calls to the function from ios? I am guided by the header file that is created in the include folder, but maybe I need to make calls in a different way

**Comment by stackchain** [comment]
hey, @Eztero you can check `yoroi-mobile` repository over there you will see how we invoke those functions, closing for now, since there's not much we can do.
